### ISSUE TITLE
Relative paths to images in markdown causing errors

### ISSUE THREAD

**Issue by djedi** [google/eleventy-high-performance-blog#18]
1. Add an image named `image.jpg` to the posts directory
2. Edit blog post `firstpost.md`, insert `![image](./image.jpg)`

Notice it will break the build with an error like:
```text
[0] Error writing templates: (more in DEBUG output)
[0] > Having trouble writing template: _site/posts/firstpost/index.html
[0] 
[0] `TemplateWriterWriteError` was thrown
[0] > ENOENT: no such file or directory, open '/path/to/blog/_site/image.jpg'
```

**Comment by djedi** [comment]
Nevermind, I see how 11ty handles images now. :(

**Comment by cramforce** [comment]
FWIW there was an issue and I fixed it. I'd recommend putting images in the img folder nonetheless.

**Comment by djedi** [comment]
Cool! I’ll check it out. Thanks!

**Comment by djedi** [comment]
I tried it out, I'm still getting the same result. I can't link to images with a relative path.

**Comment by cramforce** [comment]
There is an example at the end of this https://raw.githubusercontent.com/google/eleventy-high-performance-blog/main/posts/secondpost.md

How is your's looking?

**Comment by djedi** [comment]
Each of my blog posts are in their own directory. Within that directory I have another directory named `images`. In my markdown file I will link to the image with something like `![banner](./images/banner.jpg)`

**Comment by cramforce** [comment]
Relative URLs are resolved here https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/img-dim.js#L47

Would you mind adding a few `console.log` statements to see what URLs are being generated in your case?

**Comment by djedi** [comment]
`[0] ENOENT: no such file or directory, open '/Users/dustin/src/p/newblog/_site/posts/2020-09-21-wildcard-lets-encrypt-ssl-cert-on-synology-nas/images/banner.jpg' /posts/2020-09-21-wildcard-lets-encrypt-ssl-cert-on-synology-nas/images/banner.jpg`

<img width="710" alt="index_md_—_newblog" src="https://user-images.githubusercontent.com/177353/94493757-bce31980-01aa-11eb-81c3-5715a66f172b.png">

**Comment by cramforce** [comment]
`/Users/dustin/src/p/newblog/_site/posts/2020-09-21-wildcard-lets-encrypt-ssl-cert-on-synology-nas/images/banner.jpg` looks right, no?

Did you configure eleventy to copy your images into the _site directory?

**Comment by djedi** [comment]
I tried adding this `eleventyConfig.addPassthroughCopy("**/*.jpg");` That seemed to work to show the images, but it threw a number of other errors in the process.

**Comment by cramforce** [comment]
Unfortunately, I don't know how to make that work. It is more of a general eleventy question.

**Comment by djedi** [comment]
OK, no problem. Thanks for your help. I do a bit more research.

**Comment by dhananjayhegde** [comment]
> I tried adding this `eleventyConfig.addPassthroughCopy("**/*.jpg");` That seemed to work to show the images, but it threw a number of other errors in the process.

this saved my day today. I was struggling with it for 2 days.  Problem was I had not creatd separe folder for each post when I migrated my wordpress XML to markdowns.  Looking at your image above, realized my mistake.  

also, I had to change the addPassthrough like below

```js 
eleventyConfig.addPassthroughCopy("./images/*.jpg");
eleventyConfig.addPassthroughCopy("./images/*.png");
```
Once I did that, it worked as expected.  thank you so much
